version: '3.8'
services:
  db:
    image: ghusta/postgres-world-db:2.12
    container_name: postgres_sample_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:1.53
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14268:14268"
    restart: always

volumes:
  pgdata: