version: '3.8'
services:
  db:
    image: ghusta/postgres-world-db:2.12
    container_name: postgres_sample_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: